
export const projects1 = [
    {
        num: "01",
        category: "Video Game Project",
        title: "Alien: Nemesis",
        icon: "/assets/work/AlienLogo.png", // ✅ new field
        status: "Published",
        description: "Alien: Nemesis is a fast paced shooter with exploration, narrative, & fast paced combat. Developed by Shadow Wizard Games Studios, a team of 23 students",
        stack: [{ name: "C" }, { name: "Maya" }, { name: "Adobe" }, { name: "OpenGL" }, { name: "Photoshop" }, { name: "Figma" }, { name: "Wwise" }, { name: "Trello" }],
        image: "/assets/work/AlienNemesis.gif",
        live: "https://shadow-wizard-games.github.io/Alien-Nemesis-Website/RylanGraham.html",
        github: "https://github.com/Shadow-Wizard-Games/TheOneEngine",
    },
    {
        num: "02",
        category: "Video Game Project",
        title: "Hyper Strike",
        icon: "/assets/work/HyperLogo.png", // ✅ new field
        status: "In-Development",
        description: "HyperStrike is a fast-paced 5v5 multiplayer football game built on UDP & TCP Protocols, with high mobility movement that allows players to run on the walls, obstacles, and much more in the stadium.",
        stack: [{ name: "Unity" }, { name: "UDP" }, { name: "TCP" }, { name: "Maya" }, { name: "Adobe" }, { name: "VisualStudio" }, { name: "Github" },],
        image: "/assets/work/HyperStrikeLogo.png",
        live: "https://github.com/Historn/NetworksProject",
        github: "https://github.com/Historn/NetworksProject",
    },
    {
        num: "03",
        category: "VertX Game Engine",
        title: "VertX Game Engine",
        status: "Published Software",
        description: "Fully functional Game Engine developed using OpenGL framework, with additional libraries. Supports FBX rendering, texturing, Game Objects management, camera controls as of latest release.",
        stack: [{ name: "C" }, { name: "OpenGL" }, { name: "SDL2" }, { name: "VisualStudio" }, { name: "Github" }, ],
        image: "/assets/work/VertX.gif",
        icon: "/assets/work/VertXLogo.png", // ✅ new field
        live: "https://citm-upc.github.io/VertX-Game-Engine/",
        github: "https://github.com/CITM-UPC/VertX-Game-Engine",
    },
    {
        num: "04",
        category: "Game AI",
        title: "Game AI",
        status: "Academic Demonstration",
        description: "Exercises in Unity Environments created to highlight usage of Game AI. Behaviors featured include Pathfinding, Random Wandering, Flocking, Behavior Bricks, and Camera Frustrum Detection.",
        stack: [{ name: "C" }, { name: "Unity" }, { name: "Maya" }, { name: "Python" }, { name: "Github" },],
        image: "/assets/work/gameai.gif",
        icon: "/assets/work/AILogo.png", // ✅ new field
        live: "https://rylanjgraham.github.io/GameAI_Exercises/",
        github: "https://github.com/RylanJGraham/GameAI_Exercises",
    },
    {
        num: "05",
        category: "Unity Audio Systems",
        title: "Unity Audio",
        status: "Academic Demonstration",
        description: "Unity scene demonstrating proper usage of spatial audio, track-blending, atmospheric audio, track-layer, audio-mixing, and region specific filtering.",
        stack: [{ name: "C" }, { name: "Unity" }, { name: "Github" }, { name: "VisualStudio" },],
        image: "/assets/work/DigitalAudio.gif",
        icon: "/assets/work/DigitalLogo.png", // ✅ new field
        live: "https://play.unity.com/mg/other/webgl-builds-404826",
        github: "https://github.com/AdriaPm/DigitalAudio_UnityScene",
    },
    {
        num: "06",
        category: "Worms Replica",
        title: "Worms Replica",
        status: "Released",
        description: "Worms game title replica. Physics Engine was original and created using classroom learnings. Concepts: Drag Force, Projectile Motion, Ballistics, & Gravitational Elements.",
        stack: [{ name: "C" }, { name: "SDL2" }, { name: "Github" }, { name: "VisualStudio" }],
        image: "/assets/work/Worms.png",
        icon: "/assets/work/WormsIcon.png", // ✅ new field
        live: "https://github.com/Historn/WormsGameProject",
        github: "https://github.com/Historn/WormsGameProject",
    },
    {
        num: "07",
        category: "The ToyBox",
        title: "The ToyBox",
        status: "Released",
        description: "8 man RPG project, complete with fully operational UI, Combat, Exploration & more. Developed by hand drawn artwork. Expected Launch May 2023. Culminating Year 2 Degree Project.",
        stack: [{ name: "C" }, { name: "SDL2" }, { name: "Github" }, { name: "VisualStudio" }, { name: "Figma" }, { name: "Photoshop" }, { name: "Mondays" }, ],
        image: "/assets/work/toyboxgif.gif",
        icon: "/assets/work/ToyboxLogo.png", // ✅ new field
        live: "https://fun-makers-studios.github.io/Project2_TheToyBox/",
        github: "https://github.com/Fun-Makers-Studios/Project2_TheToyBox",
    },
    {
        num: "08",
        category: "Beta Release",
        title: "UDP & TCP Sessions",
        status: "Academic Demonstration",
        description: "Unity scene with UDP & TCP lobby connection for Client-Server. Player is located in server room, wit room creation supporting Room Naming, Usernames, Custom IP Address, User Port Information, & Active Users. Also provides real-time Client to Client Messaging via Server Routing. Able to support multiple client connections to the same server via multithreading based on users.",
        stack: [{ name: "Unity" }, { name: "C" }, { name: "UDP" }, { name: "TCP" }, ],
        image: "/assets/work/Sockets.png",
        icon: "/assets/work/TCPLogo.png", // ✅ new field
        live: "https://github.com/RylanJGraham/Connections_UnityExercise",
        github: "https://github.com/RylanJGraham/Connections_UnityExercise",
    },
    {
        num: "08",
        category: "Beta Release",
        title: "Knights Vow",
        status: "Released",
        description: "2D Platformer title, where you play as a Knight seeking to find and collect chests throughout the map. Enjoy exploring and jumping along the 8-bit platforms as you traverse the landscape. Fully functional with pathfinding, save states, collisions, and more. ",
        stack: [{ name: "C" }, { name: "VisualStudio" }, { name: "SDL2" }, ],
        image: "/assets/work/KnightsVowFS.png",
        icon: "/assets/work/KnightsVowIcon.jpg", // ✅ new field
        github: "https://github.com/RylanJGraham/Game_Development_Project1#readme",
    },
    {
        num: "09",
        category: "Retro Pinball",
        title: "Retro Pinball",
        status: "Released",
        description: "Game created using Box2D Physics Libraries and SDL Libraries on Microsoft Visual Studio. Created to demonstrate collision physics understanding.",
        stack: [{ name: "C" }, { name: "SDL2" }, { name: "Github" }, { name: "VisualStudio" }, { name: "Photoshop" } ],
        image: "/assets/work/pinballgif.gif",
        icon: "/assets/work/Pinball.png", // ✅ new field
        live: "https://github.com/AdriaPm/Pinball-Game",
        github: "https://github.com/AdriaPm/Pinball-Game",
    },
    {
        num: "10",
        category: "Snow Race",
        title: "Snow Race",
        status: "Released",
        description: "Simple 3D racing car game created for Physics II subject at CITM-UPC university. Using Bullet3D collision and aerodynamic forces. OpenGL rendering for game & camera elements. ",
        stack: [{ name: "C" }, { name: "SDL2" }, { name: "Github" }, { name: "VisualStudio" }, { name: "OpenGL" } ],
        image: "/assets/work/car.png",
        icon: "/assets/work/SnowLogo.png", // ✅ new field
        live: "https://github.com/AdriaPm/RaceCarGame3D",
        github: "https://github.com/AdriaPm/RaceCarGame3D",
    },
    {
        num: "11",
        category: "WindJammers Replica",
        title: "WindJammers Replica",
        status: "Released",
        description: "WindJammers replica game created as first video game project at CITM-UPC university. Created using C++, SDL2, and title original sprites.",
        stack: [{ name: "C" }, { name: "SDL2" }, { name: "Github" }, { name: "VisualStudio" },],
        image: "/assets/work/Windjammers.png",
        icon: "/assets/work/WindJammersLogo.png", // ✅ new field
        live: "https://github.com/AdriaPm/RaceCarGame3D",
        github: "https://github.com/AdriaPm/RaceCarGame3D",
    },
    // Add more projects for this category if needed
];

export const projects2 = [
    {
        num: "02",
        category: "3D Art & Animation",
        title: "Qatar 2022",
        description: "The Qatar 2022 Data Visualization is a web application created to demonstrate Argentina's path to victory in the 2022 Fifa World Cup from a data standpoint. Developed using React, in combination with Material UI, X-Charts, and ReCharts, the web app hopes to provide users with a clean and intuitive data journey throughout the tournament. Check it out!",
        stack: [{ name: "Vercel" }, { name: "React" }, { name: "TypeScript" }, { name: "Material" }, { name: "XCharts" }, { name: "Kaggle" }, { name: "Excel" }, { name: "Figma" },],
        image: "/assets/work/QatarDEMO.png",
        image2: "/assets/work/QatarDEMO.png", // bottom screen
        status: "Live",
        icon: "/assets/work/QatarLogo.png", // ✅ new field
        live: "https://worldcup2022datavisualized.vercel.app",
        github: "https://github.com/RylanJGraham/world_cup_2022_datavisualized",
    },
    {
        num: "01",
        category: "Beta Release",
        title: "PokéRest",
        status: "Live",
        icon: "/assets/work/PokerestIcon.png", // ✅ new field
        description: "PokéRest is a full-stack web application created in 6 hrs using Next.js, TypeScript, Shadcn-UI, and restAPI calls to PokeAPI. The project features dynamic routing, search filtering, clean UI, and optimized API retrievals to ensure a functional and superb user experience.",
        stack: [{ name: "Vercel" }, { name: "Nextjs" }, { name: "TypeScript" }, { name: "Shadcn" }, { name: "restAPI" }, { name: "Tailwind" }],
        image: "/assets/work/poke.png",
        live: "https://pokerest-app.vercel.app/",
        github: "https://github.com/RylanJGraham/pokerest",
    },
    {
        num: "05",
        category: "Beta Release",
        title: "SummAIrize",
        status: "Live",
        description: "Article Summarizer built using OpenAI GPT model, Takes article url and provides a concise summary.​",
        stack: [{ name: "React" }, { name: "OpenAI" }, { name: "Vite" }, { name: "RTKQuery" }, { name: "Tailwind" }, { name: "JavaScript" },],
        image: "/assets/work/summaraize.gif",
        live: "https://iridescent-blancmange-7bcd57.netlify.app/",
        github: "https://github.com/RylanJGraham/AI-ArticleSummarizer",
    },
    {
        num: "05",
        category: "Beta Release",
        title: "Ticket Vendor Front-End",
        status: "Front-End Repo",
        description: "An HTML & CSS project to demonstrate improved ability in HTML workflow, and usage of JavaScript. Created as proposal pitch for ticket vendor application. ​",
        stack: [{ name: "VisualStudio" }, { name: "HTML" }, { name: "Javascript" }, { name: "Tailwind" },],
        image: "/assets/work/ticketvendor.gif",
    },
    {
        num: "05",
        category: "Beta Release",
        title: "Youtube Front-End",
        status: "Front-End Repo",
        description: "An HTML & CSS Learning project, with a polished final product​",
        stack: [{ name: "HTML" }, { name: "CSS" }, { name: "ViSUALSTUDIO" },],
        image: "/assets/work/youtubeclone.gif",
    },
    
    // Add more projects for this category if needed
];

export const projects3 = [
    {
        num: "02",
        category: "Video Game Project",
        title: "Rauxa",
        description: "The Tinder for Spontaneous Meetups! Rauxa is an innovative mobile app that helps users find events and connect with people based on their preferences and location. Rauxa aims to be Barcelona's first choice in social apps",
        stack: [{ name: "Expo" }, { name: "Firebase" }, { name: "Github" }, { name: "React" }, { name: "Figma" }, { name: "Gemini" },],
        image: "/assets/work/Rauxa.png",
        icon: "/assets/work/TFG.png", // ✅ new field
        status: "In-Development",
    },
    {
        num: "01",
        category: "UI/UX Design Project",
        title: "PrimaveraPulse",
        description: "Primavera Pulse serves as a gamified app companion for the global music festival: Primavera Sound. Using gamified mechanics users can explore & enjoy the festival more, with nice rewards!",
        stack: [{ name: "Figma" }, { name: "Photoshop" }, { name: "Excel" }, { name: "GoogleSlides" }],
        image: "/assets/work/PrimaveraShort.png",
        status: "Pitching",
        icon: "/assets/work/PrimaveraIcon.png", // ✅ new field
        live: "https://www.figma.com/proto/Lw3BcdaDKPdpsI7yrEcaTz/Primavera-Pulse?node-id=2-545&t=TqmqKKVTSYVCKREP-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2%3A545&show-proto-sidebar=1",
        github: "https://docs.google.com/presentation/d/e/2PACX-1vQ4OOGAp8degVyu6s6ZQam5bzvV003IzNlAJzUXgv6xE5x6Fnj0sUQ70bbtuGCEAG_2jJ-cnFsA_DI3/pub?start=false&loop=false&delayms=3000",
    },
    {
        num: "02",
        category: "Beta Release",
        title: "CulinARy",
        status: "Published",
        description: "CulinARy is an Augmented Reality application destined for the restaurant business so the clients can take a look at the menu in 3D.",
        stack: [{ name: "Unity" }, { name: "C" }, { name: "ar" }, { name: "Firebase" },],
        image: "/assets/work/CulinARyDEMO.png",
        icon: "/assets/work/CulinARyLogo.png", // ✅ new field
        live: "https://docs.google.com/presentation/d/e/2PACX-1vR9q7x3w2LP341kqw8nD46yVIxdH2BqrM2SisEVlhsX0PatrdA16s_s5U2EJNFikF_v3SLrOPccUsze/pub?start=true&loop=false&delayms=10000",
        github: "https://github.com/RylanJGraham/CulinARy",
    },
    {
        num: "03",
        category: "UI/UX Design Project",
        title: "Minted",
        status: "Pitching",
        description: "Minted is an in-production ticket resell application for students that allows users to re-sell their ticket entries to clubs, concerts, private events & more, all in an easy to use and intuitive way. ",
        stack: [{ name: "FlutterFlow" }, { name: "Firebase" }, { name: "Stripe" }, { name: "maps" }],
        image: "/assets/work/MintedDEMO.png",
        icon: "/assets/work/MintedLogo.png", // ✅ new field
        live: "https://docs.google.com/presentation/d/e/2PACX-1vTE381nkor09xuH4XrNJQyMgvnPa0dNorb1Lkd6aeM6d2nayW3PBJdV_CPzFFFmdpYtnty-5qO9ZF6W/pub?start=false&loop=false&delayms=10000",
        github: "https://docs.google.com/presentation/d/e/2PACX-1vTE381nkor09xuH4XrNJQyMgvnPa0dNorb1Lkd6aeM6d2nayW3PBJdV_CPzFFFmdpYtnty-5qO9ZF6W/pub?start=false&loop=false&delayms=10000",
    },
    {
        num: "04",
        category: "Beta Release",
        title: "WeatherTune",
        status: "Published",
        description: "WeatherTune is a sleek and intuitive weather forecast app developed by a team of four students from CITM-UPC University. Stay ahead of the weather with accurate forecasts and a delightful user experience.",
        stack: [{ name: "Flutter" }, { name: "Dart" }, { name: "Figma" }, { name: "Firebase" }, { name: "Rapid" }, { name: "maps" }],
        image: "/assets/work/WeatherDEMO.png",
        icon: "/assets/work/WeatherLogo.png", // ✅ new field
        live: "https://github.com/RylanJGraham/WeatherTune",
        github: "https://github.com/RylanJGraham/WeatherTune",
    },
    {
        num: "02",
        category: "Video Game Project",
        title: "Terranex",
        status: "Pitching",
        description: "Terranex is a cutting-edge farm management platform designed to tackle the challenges small and medium-sized farms face in Catalonia, Spain.",
        stack: [{ name: "Excel" }, { name: "GoogleSlides" }, { name: "Figma" }, { name: "Photoshop" },],
        image: "/assets/work/TerranexShort.png",
        icon: "/assets/work/TerranexLogo.png", // ✅ new field
        live: "https://shadow-wizard-games.github.io/Alien-Nemesis-Website/index.html",
        github: "https://github.com/Shadow-Wizard-Games/TheOneEngine",
    },
    
    {
        num: "04",
        category: "UI/UX Design Project",
        title: "Edu.Cation",
        status: "In-Development",
        description: "Edu.Cation is a learning app that helps to revolutionize the education space. Incorporating fun & practicality to help teachers send their learning home.",
        stack: [{ name: "Figma" }, { name: "GoogleSlides" }],
        image: "/assets/work/EducationDEMO.png",
        icon: "/assets/work/EduLogo.png", // ✅ new field
        live: "https://docs.google.com/presentation/d/e/2PACX-1vTJUC_VmrFcPBi26BB6Ekuro1cC8ffbbWhU_r6R3gdbUV7gaN4-O11v5V2Rk2JsAF9EY0uyH0iqoWBE/pub?start=false&loop=false&delayms=10000",
        github: "https://docs.google.com/presentation/d/e/2PACX-1vTJUC_VmrFcPBi26BB6Ekuro1cC8ffbbWhU_r6R3gdbUV7gaN4-O11v5V2Rk2JsAF9EY0uyH0iqoWBE/pub?start=false&loop=false&delayms=10000",
    },
    // Add more projects for this category if needed
];

export const projects4 = [
    {
        num: "01",
        category: "3D Art & Animation",
        title: "Studio Ghibli 3D Environment",
        description: "3D Environment created using the Unity Engine, inspired by the Studio Ghibli film: Spirited Away. Explore the scene, with fbx's created using Maya, and painted with Substance Painter & Z-brush. FBX models created following protocols for tri-management, featuring LOD detailing, & more! Custom Camera optimization and shader rendering through scripting using C++.",
        stack: [{ name: "Maya" }, { name: "Unity" }, { name: "Substance" }, { name: "Photoshop" }, { name: "C" }],
        image: "/assets/work/ghibli.gif",
        live: "https://rylangraham02.wixsite.com/website/team-1",
        github: "https://github.com/RylanJGraham/Unity_Scene-Spirited-Away",
    },
    {
        num: "02",
        category: "3D Art & Animation",
        title: "Mummy FBX Animations",
        description: "FBX model animations created in Maya. Completed FBX rigging, using joints & skeletal structuring. Completed animations using fundamentals of animation, all while maintaining model integrity.",
        stack: [{ name: "Maya" }, { name: "Unity" }, { name: "Substance" }, { name: "Photoshop" }, { name: "C" }],
        image: "/assets/work/kingtut.gif",
        github: "https://github.com/RylanJGraham/3D_Animations_Unity",
    },
    {
        num: "03",
        category: "Raikou Textured FBX",
        title: "Raikou Textured FBX",
        description: "Low-poly model and high poly modeling on 3DS-Max. Painting on Zbrush, unwrapping and lighting using UVLayout and 3DSMAX. ",
        stack: [{ name: "DSMax" }, { name: "Substance" }, { name: "Blender" }, { name: "Zbrush" }],
        image: "/assets/work/raikou.jpg",
        live: "https://docs.google.com/document/d/e/2PACX-1vQy6Co0dpBb8juPjImHzrmheLdkyvuH70GU3kPwEp8W2Av3AjBtfxpa6V371ALjzFABdO8j-lW13ixP/pub",
    },
    {
        num: "04",
        category: "3D Art & Animation",
        title: "Penguin 2D Animation",
        description: "Collection of Hand-Drawn Animations completed over various timeframes. Work with Frame by Frame, Pegs, and more animation fundamentals.",
        stack: [{ name: "ToonBoom" }, { name: "Photoshop" }, { name: "Wacom" }],
        image: "/assets/work/penguin.gif",
        live: "https://rylangraham02.wixsite.com/website/copy-of-lab-work",
    },
    {
        num: "05",
        category: "3D Art & Animation",
        title: "Baker House",
        description: "​Painted Maya 3D model of island home. Project released on sketchfab complete with material maps, UV-layout, and model. Completed in 6 hours of work.",
        stack: [{ name: "Maya" }, { name: "Substance" }, { name: "Photoshop" }, { name: "Blender" }, { name: "Sketchfab" }],
        image: "/assets/work/bakerhouse.png",
        live: "https://sketchfab.com/3d-models/graham-rylan-diorama-ca883fbcfc714696a1e869d70d7a4a3b?utm_medium=embed&utm_campaign=share-popup&utm_content=ca883fbcfc714696a1e869d70d7a4a3b",
        github: "https://github.com/RylanJGraham/EnvironmentPracticeUnityScene",
    },
    {
        num: "05",
        category: "",
        title: "Hand Sketches",
        description: "Drawn using a drawing tablet on Adobe Photoshop. Collection includes practice sketches hand anatomy. No prior experience in sketching.",
        stack: [{ name: "WACOM" }, { name: "Photoshop" },],
        image: "/assets/work/HandIllustrations.png",
        live: "https://sketchfab.com/3d-models/graham-rylan-diorama-ca883fbcfc714696a1e869d70d7a4a3b?utm_medium=embed&utm_campaign=share-popup&utm_content=ca883fbcfc714696a1e869d70d7a4a3b",
        github: "https://github.com/RylanJGraham/EnvironmentPracticeUnityScene",
    },
    {
        num: "05",
        category: "",
        title: "Female Portrait Sketches",
        description: "Drawn using a drawing tablet on Adobe Photoshop. Collection includes practice sketches hand anatomy. No prior experience in sketching.",
        stack: [{ name: "WACOM" }, { name: "Photoshop" },],
        image: "/assets/work/Portraits.png",
        live: "https://sketchfab.com/3d-models/graham-rylan-diorama-ca883fbcfc714696a1e869d70d7a4a3b?utm_medium=embed&utm_campaign=share-popup&utm_content=ca883fbcfc714696a1e869d70d7a4a3b",
        github: "https://github.com/RylanJGraham/EnvironmentPracticeUnityScene",
    },
    {
        num: "05",
        category: "",
        title: "Fbx Props",
        description: "Created weapon fbx textured assets for guns within the Alien Nemesis title.",
        stack: [{ name: "Maya" }, { name: "Adobe" },],
        image: "/assets/work/gun2.png",
        live: "",
    },
    {
        num: "05",
        category: "",
        title: "Character FBX Animations",
        description: "Created character animations for 4+ characters within the Alien Nemesis title.",
        stack: [{ name: "Maya" }, { name: "Adobe" },],
        image: "/assets/work/Anarchist_Scan_Animation_DEMO.gif",
        live: "",
    },
    {
        num: "05",
        category: "",
        title: "Modular Kits",
        description: "Created character animations for 4+ characters within the Alien Nemesis title.",
        stack: [{ name: "Maya" }, { name: "Adobe" },],
        image: "/assets/work/BossLvl_ModKit_Demo.gif",
        live: "",
    },
    {
        num: "05",
        category: "",
        title: "Pixel Artwork",
        description: "Created character pixel artwork for Majora's mask 2D",
        stack: [{ name: "Aseprite" },],
        image: "/assets/work/Majora.png",
        live: "",
    },
    // Add more projects for this category if needed
];

export const projects5 = [
    {
        num: "01",
        category: "Full Stack App Project",
        company: "VRAIn Medical",
        logo: "/assets/work/VRAIn_Main_Logo.png",
        title: "Software Developer & Image Intern",
        description: "Working with VRAIn on development of key product lines. Assisting with application development, prototyping, business analytics, and image editing.",
        stack: [{ name: "Astro" }, { name: "Unity" }, { name: "Figma" }, { name: "Excel" }, { name: "Firebase" },  { name: "Docker" }, { name: "Photoshop" }  ],
        image: "/assets/work/VRAIN.png",
        live: "https://vrain-medical.com/",
        github: "https://www.cupraofficial.es/",
    },
    {
        num: "01",
        category: "Full Stack App Project",
        company: "SEAT Cupra",
        logo: "/assets/work/Cupra-SEAT.png",
        title: "ML Software Developer Intern",
        description: "Worked with SEAT-Cupra to develop advanced machine learning solutions for UI/UX. Project was created using QLearning, PyTorch, Unity Engine, and Supabase PostgreSQL",
        stack: [{ name: "PyTorch" }, { name: "Unity" }, { name: "Python" }, { name: "Supabase" }, { name: "C" } ],
        image: "/assets/work/intern.png",
        live: "https://www.cupraofficial.es/",
        github: "https://www.cupraofficial.es/",
    },
    {
        num: "02",
        category: "Video Game Project",
        company: "Catedra SEAT-UPC",
        logo: "/assets/work/ctedraupc.png",
        title: "SEAT-Cupra UPC Catedra Gamified Car",
        description: "Created a gamified car application to improve the user driving experience. Developed a prototype & presented to SEAT-Cupra & EDAG departments. Worked in a team of 4 people from similar backgrounds.",
        stack: [{ name: "Figma" }, { name: "Unity" }, { name: "C" }, { name: "Photoshop" }, { name: "Slides" }],
        image: "/assets/work/gamified.png",
        live: "https://www.citm.upc.edu/blog/presentacion-de-los-proyectos-cupra-gamified-car/",
        github: "https://www.citm.upc.edu/blog/presentacion-de-los-proyectos-cupra-gamified-car/",
    },
    // Add more featured projects if needed
];

export const projects6 = [
    {
        num: "01",
        category: "Beta Release",
        title: "Unity Debug Tool",
        description: "The Unity Debug Tool to be used by Unity Game Developers to gain real-time insights into player, enemy, or game-state data. Currently featuring heatmap, and prefab generation for player deaths, damage, & enemy states, with customizable coloring, scaling, intensity and more!",
        stack: [{ name: "Unity" }, { name: "MySQL" }, { name: "PHP" }, { name: "C" }, ],
        image: "/assets/work/HeatMap.png",
        live: "https://github.com/JoeyCM/Delivery3",
        github: "https://github.com/JoeyCM/Delivery3",
    },
    // Add more featured projects if needed
];

